# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dget}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Partridge"]
  s.date = %q{2009-09-21}
  s.default_executable = %q{dget}
  s.description = %q{get local copies of github project wikis}
  s.email = %q{nkpart@gmail.com}
  s.executables = ["dget"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/dget",
     "dget.gemspec",
     "lib/dget.rb",
     "lib/dget/github.html",
     "lib/dget/github.rb",
     "lib/dget/googlecode.rb",
     "lib/dget/utils.rb",
     "lib/googlecode.html",
     "spec/dget_spec.rb",
     "spec/spec_helper.rb",
     "test/test_gh-wiki.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/nkpart/dget}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{get local copies of github project wikis}
  s.test_files = [
    "spec/dget_spec.rb",
     "spec/spec_helper.rb",
     "test/test_gh-wiki.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
